DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
INFO:root:05/01/2018 13:11:00 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 23 | __init__: Initializing Measurement class.
INFO:root:05/01/2018 13:11:00 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 38 | _receive_done: Received a _TEST_PACKET
INFO:root:05/01/2018 13:11:00 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 38 | _receive_done: Received a _TEST_PACKET
INFO:root:05/01/2018 13:11:00 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 43 | _receive_done: Received a _TIME_INFO_PACKET
INFO:root:05/01/2018 13:11:00 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 38 | _receive_done: Received a _TEST_PACKET
INFO:root:05/01/2018 13:11:00 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 38 | _receive_done: Received a _TEST_PACKET
INFO:root:05/01/2018 13:11:00 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 43 | _receive_done: Received a _TIME_INFO_PACKET
INFO:root:05/01/2018 13:11:00 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 50 | _receive_done: Received a _MOISTURE_INFO_PACKET
DEBUG:peewee:('INSERT INTO "reading" ("nodeID", "timestamp", "measurement", "battery_level") VALUES (?, ?, ?, ?)', [1, datetime.datetime(2018, 5, 1, 13, 22, 19, 568742), 9, 3.28])
INFO:root:05/01/2018 13:11:00 | /home/pi/myLadybugHelper/should_i_water/collect_readings_task.py | 22 | store_measurement: Measurement stored.  nodeID: 1, measurement: 9, battery_level: 3.28
INFO:root:05/01/2018 13:11:00 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 50 | _receive_done: Received a _MOISTURE_INFO_PACKET
DEBUG:peewee:('INSERT INTO "reading" ("nodeID", "timestamp", "measurement", "battery_level") VALUES (?, ?, ?, ?)', [1, datetime.datetime(2018, 5, 2, 4, 0, 9, 794885), 147, 2.94])
INFO:root:05/01/2018 13:11:00 | /home/pi/myLadybugHelper/should_i_water/collect_readings_task.py | 22 | store_measurement: Measurement stored.  nodeID: 1, measurement: 147, battery_level: 2.94
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 2, 0, 0), datetime.datetime(2018, 5, 2, 5, 0, 28, 20515)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 200 29013
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 2, 0, 0), datetime.datetime(2018, 5, 2, 5, 0, 29, 201525)])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 2, 0, 0), datetime.datetime(2018, 5, 2, 9, 14, 17, 185548)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 200 29074
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 2, 0, 0), datetime.datetime(2018, 5, 2, 9, 14, 18, 248108)])
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ImportError: No module named 'google'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ImportError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ImportError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest
INFO:googleapiclient.discovery:URL being requested: POST https://www.googleapis.com/gmail/v1/users/me/messages/send?alt=json
INFO:oauth2client.transport:Refreshing due to a 401 (attempt 1/2)
INFO:oauth2client.client:Refreshing access_token
INFO:root:05/02/2018 09:14:18 | /home/pi/myLadybugHelper/should_i_water/mail_providers_lib.py | 86 | _send_message: Message sent. ID = 16321a211b93a06a
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 2, 0, 0), datetime.datetime(2018, 5, 2, 9, 20, 26, 631826)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 200 29154
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 2, 0, 0), datetime.datetime(2018, 5, 2, 9, 20, 27, 822141)])
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ImportError: No module named 'google'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ImportError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ImportError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest
INFO:googleapiclient.discovery:URL being requested: POST https://www.googleapis.com/gmail/v1/users/me/messages/send?alt=json
INFO:root:05/02/2018 09:20:27 | /home/pi/myLadybugHelper/should_i_water/mail_providers_lib.py | 86 | _send_message: Message sent. ID = 16321a7b36764afe
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 23 | __init__: Initializing Measurement class.
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 38 | _receive_done: Received a _TEST_PACKET
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 38 | _receive_done: Received a _TEST_PACKET
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 38 | _receive_done: Received a _TEST_PACKET
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 43 | _receive_done: Received a _TIME_INFO_PACKET
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 38 | _receive_done: Received a _TEST_PACKET
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 38 | _receive_done: Received a _TEST_PACKET
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 43 | _receive_done: Received a _TIME_INFO_PACKET
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 50 | _receive_done: Received a _MOISTURE_INFO_PACKET
DEBUG:peewee:('INSERT INTO "reading" ("nodeID", "timestamp", "measurement", "battery_level") VALUES (?, ?, ?, ?)', [1, datetime.datetime(2018, 5, 2, 17, 19, 19, 501073), 405, 4.2])
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_task.py | 22 | store_measurement: Measurement stored.  nodeID: 1, measurement: 405, battery_level: 4.2
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 50 | _receive_done: Received a _MOISTURE_INFO_PACKET
DEBUG:peewee:('INSERT INTO "reading" ("nodeID", "timestamp", "measurement", "battery_level") VALUES (?, ?, ?, ?)', [1, datetime.datetime(2018, 5, 3, 4, 0, 9, 869105), 138, 4.14])
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_task.py | 22 | store_measurement: Measurement stored.  nodeID: 1, measurement: 138, battery_level: 4.14
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 3, 0, 0), datetime.datetime(2018, 5, 3, 5, 0, 14, 697130)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 403 10
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 200 29564
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 200 29563
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 200 29563
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL, "threshold" INTEGER NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 3, 0, 0), datetime.datetime(2018, 5, 3, 14, 32, 0, 237311)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 50 | _receive_done: Received a _MOISTURE_INFO_PACKET
DEBUG:peewee:('INSERT INTO "reading" ("nodeID", "timestamp", "measurement", "battery_level") VALUES (?, ?, ?, ?)', [1, datetime.datetime(2018, 5, 4, 4, 0, 8, 747100), 200, 4.03])
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_task.py | 22 | store_measurement: Measurement stored.  nodeID: 1, measurement: 200, battery_level: 4.03
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL, "threshold" INTEGER NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 4, 0, 0), datetime.datetime(2018, 5, 4, 5, 0, 14, 343267)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 200 32710
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 4, 0, 0), datetime.datetime(2018, 5, 4, 5, 0, 15, 741401)])
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ImportError: No module named 'google'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ImportError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ImportError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest
INFO:googleapiclient.discovery:URL being requested: POST https://www.googleapis.com/gmail/v1/users/me/messages/send?alt=json
INFO:oauth2client.transport:Refreshing due to a 401 (attempt 1/2)
INFO:oauth2client.client:Refreshing access_token
INFO:root:05/04/2018 05:00:15 | /home/pi/myLadybugHelper/should_i_water/mail_providers_lib.py | 86 | _send_message: Message sent. ID = 1632b0632585125a
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL, "threshold" INTEGER NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 4, 0, 0), datetime.datetime(2018, 5, 4, 5, 12, 54, 836329)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL, "threshold" INTEGER NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 4, 0, 0), datetime.datetime(2018, 5, 4, 10, 11, 27, 969108)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 200 29370
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 4, 0, 0), datetime.datetime(2018, 5, 4, 10, 11, 29, 85879)])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL, "threshold" INTEGER NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 4, 0, 0), datetime.datetime(2018, 5, 4, 10, 14, 41, 521289)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 200 29370
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 4, 0, 0), datetime.datetime(2018, 5, 4, 10, 14, 42, 510561)])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL, "threshold" INTEGER NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL, "threshold" INTEGER NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 4, 0, 0), datetime.datetime(2018, 5, 4, 10, 20, 24, 956943)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL, "threshold" INTEGER NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 4, 0, 0), datetime.datetime(2018, 5, 4, 10, 20, 53, 500531)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL, "threshold" INTEGER NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 4, 0, 0), datetime.datetime(2018, 5, 4, 10, 22, 5, 192584)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 200 29344
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 4, 0, 0), datetime.datetime(2018, 5, 4, 10, 22, 6, 273119)])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL, "threshold" INTEGER NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 4, 0, 0), datetime.datetime(2018, 5, 4, 10, 22, 55, 301518)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 200 29343
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 4, 0, 0), datetime.datetime(2018, 5, 4, 10, 23, 11, 221172)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 200 29342
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL, "threshold" INTEGER NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL, "threshold" INTEGER NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 200 29344
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 4, 0, 0), datetime.datetime(2018, 5, 4, 10, 30, 25, 983841)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 4, 0, 0), datetime.datetime(2018, 5, 4, 10, 30, 37, 467636)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL, "threshold" INTEGER NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 200 29345
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 4, 0, 0), datetime.datetime(2018, 5, 4, 10, 32, 45, 375449)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 4, 0, 0), datetime.datetime(2018, 5, 4, 10, 32, 57, 958096)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL, "threshold" INTEGER NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 4, 0, 0), datetime.datetime(2018, 5, 4, 10, 38, 38, 632693)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL, "threshold" INTEGER NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 4, 0, 0), datetime.datetime(2018, 5, 4, 10, 39, 43, 575778)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 50 | _receive_done: Received a _MOISTURE_INFO_PACKET
DEBUG:peewee:('INSERT INTO "reading" ("nodeID", "timestamp", "measurement", "battery_level") VALUES (?, ?, ?, ?)', [1, datetime.datetime(2018, 5, 5, 4, 0, 7, 490911), 171, 3.95])
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_task.py | 22 | store_measurement: Measurement stored.  nodeID: 1, measurement: 171, battery_level: 3.95
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL, "threshold" INTEGER NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 200 29712
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 5, 0, 0), datetime.datetime(2018, 5, 5, 5, 0, 15, 308897)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
INFO:root:05/05/2018 05:00:15 | /home/pi/myLadybugHelper/should_i_water/mail_providers_lib.py | 122 | send_mail: Outlook email successfully sent
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 5, 0, 0), datetime.datetime(2018, 5, 5, 5, 0, 18, 190524)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ImportError: No module named 'google'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ImportError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ImportError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest
INFO:googleapiclient.discovery:URL being requested: POST https://www.googleapis.com/gmail/v1/users/me/messages/send?alt=json
INFO:oauth2client.transport:Refreshing due to a 401 (attempt 1/2)
INFO:oauth2client.client:Refreshing access_token
INFO:root:05/05/2018 05:00:18 | /home/pi/myLadybugHelper/should_i_water/mail_providers_lib.py | 86 | _send_message: Message sent. ID = 163302c98701bdef
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 50 | _receive_done: Received a _MOISTURE_INFO_PACKET
DEBUG:peewee:('INSERT INTO "reading" ("nodeID", "timestamp", "measurement", "battery_level") VALUES (?, ?, ?, ?)', [1, datetime.datetime(2018, 5, 6, 4, 0, 6, 223040), 149, 3.89])
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_task.py | 22 | store_measurement: Measurement stored.  nodeID: 1, measurement: 149, battery_level: 3.89
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL, "threshold" INTEGER NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 200 31546
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 6, 0, 0), datetime.datetime(2018, 5, 6, 5, 48, 25, 319339)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
INFO:root:05/06/2018 05:48:25 | /home/pi/myLadybugHelper/should_i_water/mail_providers_lib.py | 122 | send_mail: Outlook email successfully sent
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 6, 0, 0), datetime.datetime(2018, 5, 6, 5, 48, 27, 584892)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ImportError: No module named 'google'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ImportError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ImportError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest
INFO:googleapiclient.discovery:URL being requested: POST https://www.googleapis.com/gmail/v1/users/me/messages/send?alt=json
INFO:oauth2client.transport:Refreshing due to a 401 (attempt 1/2)
INFO:oauth2client.client:Refreshing access_token
INFO:root:05/06/2018 05:48:27 | /home/pi/myLadybugHelper/should_i_water/mail_providers_lib.py | 86 | _send_message: Message sent. ID = 163357f0aafe4bd7
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 50 | _receive_done: Received a _MOISTURE_INFO_PACKET
DEBUG:peewee:('INSERT INTO "reading" ("nodeID", "timestamp", "measurement", "battery_level") VALUES (?, ?, ?, ?)', [1, datetime.datetime(2018, 5, 7, 4, 0, 4, 958553), 151, 3.83])
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_task.py | 22 | store_measurement: Measurement stored.  nodeID: 1, measurement: 151, battery_level: 3.83
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL, "threshold" INTEGER NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 200 29350
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 7, 0, 0), datetime.datetime(2018, 5, 7, 5, 0, 15, 269148)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
INFO:root:05/07/2018 05:00:15 | /home/pi/myLadybugHelper/should_i_water/mail_providers_lib.py | 122 | send_mail: Outlook email successfully sent
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 7, 0, 0), datetime.datetime(2018, 5, 7, 5, 0, 17, 723723)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ImportError: No module named 'google'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ImportError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ImportError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest
INFO:googleapiclient.discovery:URL being requested: POST https://www.googleapis.com/gmail/v1/users/me/messages/send?alt=json
INFO:oauth2client.transport:Refreshing due to a 401 (attempt 1/2)
INFO:oauth2client.client:Refreshing access_token
INFO:root:05/07/2018 05:00:17 | /home/pi/myLadybugHelper/should_i_water/mail_providers_lib.py | 86 | _send_message: Message sent. ID = 1633a794c36ab463
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 50 | _receive_done: Received a _MOISTURE_INFO_PACKET
DEBUG:peewee:('INSERT INTO "reading" ("nodeID", "timestamp", "measurement", "battery_level") VALUES (?, ?, ?, ?)', [1, datetime.datetime(2018, 5, 8, 4, 0, 3, 672093), 174, 3.79])
INFO:root:05/02/2018 09:17:10 | /home/pi/myLadybugHelper/should_i_water/collect_readings_task.py | 22 | store_measurement: Measurement stored.  nodeID: 1, measurement: 174, battery_level: 3.79
INFO:root:05/08/2018 04:36:59 | /home/pi/myLadybugHelper/should_i_water/reading_model.py | 10 | <module>: Please set the DATABASE_FILE environment variable
INFO:root:05/08/2018 04:37:35 | /home/pi/myLadybugHelper/should_i_water/reading_model.py | 11 | <module>: Please set the DATABASE_FILE environment variable
INFO:root:05/08/2018 04:42:56 | /home/pi/myLadybugHelper/should_i_water/reading_model.py | 11 | <module>: Please set the DATABASE_FILE environment variable.
INFO:root:05/08/2018 05:03:06 | /home/pi/myLadybugHelper/should_i_water/reading_model.py | 11 | <module>: Please set the DATABASE_FILE environment variable.
INFO:root:05/08/2018 05:03:07 | /home/pi/myLadybugHelper/should_i_water/reading_model.py | 11 | <module>: Please set the DATABASE_FILE environment variable.
INFO:root:05/08/2018 05:03:08 | /home/pi/myLadybugHelper/should_i_water/reading_model.py | 11 | <module>: Please set the DATABASE_FILE environment variable.
INFO:root:05/08/2018 05:03:09 | /home/pi/myLadybugHelper/should_i_water/reading_model.py | 11 | <module>: Please set the DATABASE_FILE environment variable.
INFO:root:05/08/2018 05:03:09 | /home/pi/myLadybugHelper/should_i_water/reading_model.py | 11 | <module>: Please set the DATABASE_FILE environment variable.
INFO:root:05/08/2018 05:11:47 | /home/pi/myLadybugHelper/should_i_water/reading_model.py | 11 | <module>: Please set the DATABASE_FILE environment variable.
INFO:root:05/08/2018 05:11:48 | /home/pi/myLadybugHelper/should_i_water/reading_model.py | 11 | <module>: Please set the DATABASE_FILE environment variable.
INFO:root:05/08/2018 05:11:48 | /home/pi/myLadybugHelper/should_i_water/reading_model.py | 11 | <module>: Please set the DATABASE_FILE environment variable.
INFO:root:05/08/2018 05:11:49 | /home/pi/myLadybugHelper/should_i_water/reading_model.py | 11 | <module>: Please set the DATABASE_FILE environment variable.
INFO:root:05/08/2018 05:11:50 | /home/pi/myLadybugHelper/should_i_water/reading_model.py | 11 | <module>: Please set the DATABASE_FILE environment variable.
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL, "threshold" INTEGER NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
INFO:root:05/08/2018 09:11:26 | /home/pi/myLadybugHelper/should_i_water/collect_readings_lib.py | 23 | __init__: Initializing Measurement class.
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL, "threshold" INTEGER NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 200 29784
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 8, 0, 0), datetime.datetime(2018, 5, 8, 9, 14, 23, 907171)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
INFO:root:05/08/2018 09:14:23 | /home/pi/myLadybugHelper/should_i_water/mail_providers_lib.py | 122 | send_mail: Outlook email successfully sent
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 8, 0, 0), datetime.datetime(2018, 5, 8, 9, 14, 27, 21909)])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."description", "t1"."threshold" FROM "node" AS "t1" WHERE ("t1"."nodeID" = ?) LIMIT 1 OFFSET 0', [1])
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ImportError: No module named 'google'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ImportError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ImportError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest
INFO:googleapiclient.discovery:URL being requested: POST https://www.googleapis.com/gmail/v1/users/me/messages/send?alt=json
INFO:oauth2client.transport:Refreshing due to a 401 (attempt 1/2)
INFO:oauth2client.client:Refreshing access_token
INFO:root:05/08/2018 09:14:27 | /home/pi/myLadybugHelper/should_i_water/mail_providers_lib.py | 86 | _send_message: Message sent. ID = 16340885915ad6d9
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "node" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "description" VARCHAR(255) NOT NULL, "threshold" INTEGER NOT NULL)', [])
DEBUG:peewee:('CREATE TABLE IF NOT EXISTS "reading" ("id" INTEGER NOT NULL PRIMARY KEY, "nodeID" INTEGER NOT NULL, "timestamp" DATETIME NOT NULL, "measurement" INTEGER NOT NULL, "battery_level" REAL NOT NULL)', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 8, 0, 0), datetime.datetime(2018, 5, 8, 9, 21, 6, 279584)])
ERROR:root:05/08/2018 09:20:35 | /home/pi/myLadybugHelper/should_i_water/send_mail_lib.py | 47 | _is_a_reading : <class 'reading_model.Reading'> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0
Params: [datetime.datetime(2018, 5, 8, 0, 0), datetime.datetime(2018, 5, 8, 9, 21, 6, 279584)]
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 200 29786
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 200 29789
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 8, 0, 0), datetime.datetime(2018, 5, 8, 9, 27, 44, 639476)])
ERROR:root:05/08/2018 09:20:35 | /home/pi/myLadybugHelper/should_i_water/send_mail_lib.py | 47 | _is_a_reading : <class 'reading_model.Reading'> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0
Params: [datetime.datetime(2018, 5, 8, 0, 0), datetime.datetime(2018, 5, 8, 9, 27, 44, 639476)]
ERROR:root:05/08/2018 09:20:35 | /home/pi/myLadybugHelper/should_i_water/send_mail_lib.py | 90 | get_moisture_puck_advice : Error - a reading does not exist.
INFO:root:05/08/2018 09:27:44 | /home/pi/myLadybugHelper/should_i_water/mail_providers_lib.py | 122 | send_mail: Outlook email successfully sent
DEBUG:peewee:('SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0', [datetime.datetime(2018, 5, 8, 0, 0), datetime.datetime(2018, 5, 8, 9, 28, 1, 658302)])
ERROR:root:05/08/2018 09:20:35 | /home/pi/myLadybugHelper/should_i_water/send_mail_lib.py | 47 | _is_a_reading : <class 'reading_model.Reading'> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."nodeID", "t1"."timestamp", "t1"."measurement", "t1"."battery_level" FROM "reading" AS "t1" WHERE ("t1"."timestamp" BETWEEN ? AND ?) LIMIT 1 OFFSET 0
Params: [datetime.datetime(2018, 5, 8, 0, 0), datetime.datetime(2018, 5, 8, 9, 28, 1, 658302)]
ERROR:root:05/08/2018 09:20:35 | /home/pi/myLadybugHelper/should_i_water/send_mail_lib.py | 90 | get_moisture_puck_advice : Error - a reading does not exist.
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ImportError: No module named 'google'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ImportError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ImportError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest
DEBUG:matplotlib:$HOME=/home/pi
DEBUG:matplotlib:matplotlib data path /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data
DEBUG:matplotlib:loaded rc file /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/matplotlibrc
DEBUG:matplotlib:matplotlib version 2.2.2
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
DEBUG:matplotlib:loaded modules: ['json.decoder', '_string', 'numpy.__config__', 'difflib', '_bootlocale', 'unittest.runner', 'numpy.linalg.lapack_lite', 'types', 'urllib.parse', 'matplotlib.cbook.deprecation', '_posixsubprocess', 'numpy.lib.function_base', '_io', 'matplotlib.fontconfig_pattern', 'matplotlib.rcsetup', 'errno', 'weakref', 'numpy.testing.utils', '_ssl', 'numpy.fft.info', 'certifi.core', '_socket', 'selectors', 'distutils', 'numpy.lib.polynomial', '_locale', '_datetime', 'gzip', '_weakref', '_warnings', 'numpy.linalg', 'lzma', 'numpy.linalg.info', 'glob', 'email.errors', 'sitecustomize', '_functools', 'numpy.polynomial._polybase', 'pyparsing', 'matplotlib.cbook._backports', 'numpy._distributor_init', 'ipaddress', 'importlib._bootstrap', 'functools', 'copy', 'collections', 'json.encoder', 'importlib.machinery', '_sysconfigdata_m', 'numpy.ctypeslib', 'numpy.fft', 'operator', 'numpy.compat', 'matplotlib._version', 'gettext', 'distutils.version', 'six', 'site', 'numpy.core._internal', 'numpy.fft.fftpack_lite', 'numpy.matrixlib.defmatrix', 'numpy.core.shape_base', 'numpy.testing.nose_tools.nosetester', 'linecache', 'matplotlib.cbook', 'numpy.linalg.linalg', 'zlib', 'abc', '_signal', '_decimal', 'warnings', 'zipimport', '_weakrefset', 'collections.abc', 'numpy.testing.nose_tools.decorators', 'reprlib', 'six.moves.urllib', '_struct', 'argparse', 'random', 'numpy.lib.twodim_base', 'numpy.testing', 'numpy.polynomial.laguerre', 'traceback', 'base64', 'pathlib', '_compat_pickle', 'numpy.core', 'matplotlib.testing', 'email.feedparser', 'matplotlib', 'email.parser', 'email.message', '_bisect', 'unittest.loader', '__main__', 'handle_logging_lib', 'numpy.random.info', 'json', '_bz2', '_thread', 'numpy.lib.ufunclike', 'email.encoders', 'email._policybase', 'http.client', 'quopri', 'numpy.lib.arrayterator', 'struct', 'itertools', 'distutils.errors', 'fnmatch', 'pickle', 'numpy.testing.nosetester', 'numpy.matrixlib', 'sre_constants', '_lzma', 'rlcompleter', '_frozen_importlib_external', 'email.quoprimime', 'os.path', 'numpy.ma', '__future__', 'numpy.lib.shape_base', 'numpy.lib.utils', 'urllib.request', 'numpy.core.info', 'numpy._import_tools', 'numpy.polynomial', 'numpy.fft.helper', '_frozen_importlib', 'urllib.response', 'socket', '_random', 'heapq', 'email.utils', 'numpy.polynomial.polyutils', 'numpy.core.memmap', 'numpy.lib.stride_tricks', 'six.moves.urllib.request', 'codecs', 'email', 'bisect', 'numpy.linalg._umath_linalg', 'numpy.lib.type_check', 'hashlib', 'contextlib', 'string', 'numpy.testing.nose_tools', 'numpy.polynomial.legendre', 'numpy.lib.financial', 'uu', 'dateutil._version', 'numpy.core._methods', 'numpy.lib._datasource', 'sys', 'math', 'numpy.lib.format', '_stat', 'email.iterators', 'numpy.core.records', 'bz2', '_heapq', 'plot_weather_lib', 'numpy.polynomial.polynomial', 'ast', 'marshal', 'numpy.polynomial.hermite_e', 'keyword', 'io', 'email.charset', 'unittest.util', 'email._encoded_words', 'decimal', 'builtins', 'inspect', 'numpy.core.multiarray', 'importlib', 'importlib.abc', 'urllib.error', '_hashlib', 'numpy.polynomial.hermite', 'numpy.core.fromnumeric', 'stat', 'numpy.core.getlimits', 'numpy.random.mtrand', 'numpy.ma.extras', 'numpy.testing.decorators', '_collections', 'encodings', '_ast', 'numpy.core.function_base', 'tokenize', 'time', '_compression', 'numpy.random', '_sysconfigdata', 'select', 'unittest.result', '_ctypes', 'readline', 'unittest', 'numpy.lib.nanfunctions', 'unittest.main', 'numpy.lib', '_json', 'copyreg', 'mtrand', 'email.header', 'datetime', 'numpy', 'distutils.sysconfig', 'numpy.testing.nose_tools.utils', '_imp', 'numpy.lib.mixins', 'email.base64mime', 'textwrap', 'numpy.lib.index_tricks', 'tempfile', 'numpy.lib.arraysetops', 'numpy.compat.py3k', '_pickle', 'subprocess', 'numbers', 'unittest.signals', 'numpy.core.einsumfunc', 'numpy.lib._version', 'token', '_operator', 'shutil', 'posix', '_opcode', 'importlib._bootstrap_external', 'numpy.lib.info', 'opcode', 'dis', 'unittest.case', 'posixpath', 'encodings.latin_1', 'threading', 'cycler', 'matplotlib.compat.subprocess', 'certifi', 'http', 'numpy.lib.npyio', 'numpy.version', '_collections_abc', 'signal', 'ctypes', 'matplotlib.compat', 'email._parseaddr', 'encodings.utf_8', 'numpy.ma.core', 'numpy.core.machar', 'cython_runtime', 'enum', 'sre_parse', 'encodings.aliases', 'numpy.compat._inspect', 'numpy._globals', 'numpy.lib.scimath', 'numpy.core.numeric', 'json.scanner', 'dateutil', '_sitebuiltins', 'numpy.lib._iotools', 'six.moves', 'locale', '_sre', 'pprint', 'numpy.fft.fftpack', 'numpy.polynomial.chebyshev', 'numpy.core.numerictypes', 'matplotlib.colors', 'numpy.lib.arraypad', 'urllib', 'logging', '_codecs', 'calendar', 'ssl', 'grp', 're', 'mpl_toolkits', 'importlib.util', 'genericpath', 'numpy.core.defchararray', 'pwd', 'ctypes._endian', 'binascii', 'numpy.core.arrayprint', 'os', 'sre_compile', 'ntpath', 'matplotlib._color_data', 'sysconfig', 'unittest.suite', 'atexit', 'numpy.core.umath', 'numpy.add_newdocs']
DEBUG:matplotlib:CACHEDIR=/home/pi/.cache/matplotlib
INFO:matplotlib.font_manager:font search path ['/home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf', '/home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm', '/home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts']
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizFourSymBol.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizFourSymReg.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizTwoSymReg.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/cmtt10.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXNonUniBol.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizTwoSymBol.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/cmmi10.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/cmb10.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXGeneralBol.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXNonUniBolIta.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizThreeSymBol.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXNonUniIta.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSerif-Italic.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXGeneralItalic.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSerifDisplay.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXGeneralBolIta.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/cmr10.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSerif-Bold.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/cmss10.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSansMono-Oblique.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizThreeSymReg.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans-BoldOblique.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSansMono-BoldOblique.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans-Oblique.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSansMono-Bold.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSerif-BoldItalic.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXNonUni.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizOneSymBol.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizFiveSymReg.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/cmsy10.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizOneSymReg.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/cmex10.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXGeneral.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSansDisplay.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans-Bold.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSerif.ttf
DEBUG:matplotlib.font_manager:trying fontname /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSansMono.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizFourSymBol.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizFourSymReg.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizTwoSymReg.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/cmtt10.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXNonUniBol.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizTwoSymBol.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/cmmi10.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/cmb10.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXGeneralBol.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXNonUniBolIta.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizThreeSymBol.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXNonUniIta.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSerif-Italic.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXGeneralItalic.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSerifDisplay.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXGeneralBolIta.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/cmr10.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSerif-Bold.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/cmss10.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSansMono-Oblique.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizThreeSymReg.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans-BoldOblique.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSansMono-BoldOblique.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans-Oblique.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSansMono-Bold.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSerif-BoldItalic.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXNonUni.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizOneSymBol.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizFiveSymReg.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/cmsy10.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXSizOneSymReg.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/cmex10.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/STIXGeneral.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSansDisplay.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans-Bold.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSerif.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSansMono.ttf
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/cmsy10.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pbkli8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts/Helvetica-BoldOblique.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/putri8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/phvb8an.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/phvbo8an.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/putb8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/cmmi10.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pzcmi8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pcrb8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts/ZapfDingbats.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/phvl8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pbkl8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pcrbo8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts/Courier-BoldOblique.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts/Courier-Bold.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/putbi8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pagko8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts/Times-BoldItalic.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts/Helvetica-Bold.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts/Times-Roman.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pagk8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pagdo8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pplri8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts/Times-Italic.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pncb8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pplb8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/cmex10.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pplbi8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pplr8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/ptmb8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pbkdi8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts/Symbol.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/phvb8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pbkd8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pzdr.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts/Courier.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/cmtt10.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/cmr10.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/putr8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pncr8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/phvro8an.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts/Helvetica.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/ptmbi8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts/Helvetica-Oblique.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/phvbo8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pncbi8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/psyr.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts/Courier-Oblique.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts/Times-Bold.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pagd8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/ptmr8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/phvr8an.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/phvr8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/phvlo8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pncri8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pcrr8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/ptmri8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/pcrro8a.afm
DEBUG:matplotlib.font_manager:createFontDict: /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/afm/phvro8a.afm
INFO:matplotlib.font_manager:generated new fontManager
DEBUG:matplotlib:$HOME=/home/pi
DEBUG:matplotlib:matplotlib data path /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data
DEBUG:matplotlib:loaded rc file /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/matplotlibrc
DEBUG:matplotlib:matplotlib version 2.2.2
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
DEBUG:matplotlib:loaded modules: ['matplotlib.rcsetup', '_codecs', 'numpy.polynomial.legendre', 'importlib._bootstrap_external', 'pathlib', 'numpy.lib.arraysetops', 'json', 'matplotlib.fontconfig_pattern', 'select', 'matplotlib._version', 'ast', 'readline', 'numpy.polynomial.hermite', 'base64', 'matplotlib._color_data', 'itertools', 'numpy.version', 'numpy.core.umath', 'opcode', 'unittest.suite', '_bz2', 'pyparsing', 'glob', 'unittest.util', 'numpy.lib.utils', 'numpy.lib.nanfunctions', 'numpy.add_newdocs', 'numpy.lib.shape_base', '_warnings', '_ctypes', 're', 'collections.abc', 'numpy.lib.scimath', 'inspect', 'bisect', '_datetime', 'numpy.compat', 'grp', 'argparse', 'numpy.core.numeric', 'io', 'distutils.version', 'ipaddress', '_socket', 'http', 'numpy.fft.helper', 'numpy.testing.nose_tools.decorators', '_operator', 'string', '_bisect', 'urllib.response', 'types', 'encodings', 'certifi', 'numpy.core.memmap', 'copyreg', '_heapq', 'matplotlib', 'enum', 'marshal', 'numpy.testing.nose_tools.utils', 'subprocess', 'email.errors', 'numpy.testing.utils', '_locale', 'mpl_toolkits', 'unittest.signals', 'numpy.core.records', 'email.encoders', 'numpy.lib.arrayterator', '_hashlib', 'datetime', 'numpy.lib.polynomial', 'numpy.fft.fftpack', 'importlib', 'lzma', 'numpy.lib.type_check', 'sre_parse', '_sre', 'email.base64mime', 'gzip', 'numpy.polynomial.polyutils', '_thread', 'unittest.case', 'time', 'builtins', '_collections', 'numpy.core._internal', 'unittest.main', 'sre_compile', 'matplotlib.compat.subprocess', '_imp', 'selectors', 'numpy.linalg.info', '_sysconfigdata_m', 'numpy.polynomial.laguerre', 'json.encoder', 'numpy.testing.decorators', 'numpy.polynomial.hermite_e', 'numpy.random', 'numpy.lib._version', 'numpy.core.fromnumeric', '_functools', 'abc', 'numpy.testing.nosetester', 'collections', 'binascii', '_weakref', 'hashlib', 'bz2', 'numpy.core.einsumfunc', 'uu', 'email.message', 'distutils', 'matplotlib.cbook', 'email.utils', 'numpy.lib.npyio', '_signal', 'numpy.polynomial.chebyshev', 'site', 'matplotlib.colors', 'tempfile', 'numpy.core.defchararray', 'numpy.polynomial._polybase', 'plot_weather_lib', 'ssl', 'six.moves.urllib', '_ssl', 'numpy.lib.info', 'json.scanner', 'unittest.result', 'importlib.machinery', 'pickle', 'email._parseaddr', 'encodings.aliases', 'numpy.ma.extras', 'posixpath', 'numpy.polynomial.polynomial', 'numbers', 'sre_constants', 'functools', 'urllib.parse', 'numpy.matrixlib.defmatrix', 'mtrand', 'token', 'ctypes._endian', 'numpy.testing.nose_tools', 'email._policybase', 'email._encoded_words', 'ntpath', 'email.feedparser', 'dateutil._version', 'numpy.lib.twodim_base', '_frozen_importlib', 'contextlib', 'reprlib', 'numpy.core._methods', 'warnings', '_stat', 'email.charset', 'heapq', 'numpy.lib.index_tricks', 'quopri', 'gettext', 'zipimport', 'decimal', 'numpy.lib._datasource', 'numpy.lib._iotools', 'matplotlib.compat', 'numpy.compat._inspect', 'threading', 'locale', 'numpy.lib.function_base', 'json.decoder', 'struct', 'encodings.latin_1', 'importlib.util', 'numpy.linalg._umath_linalg', 'genericpath', 'numpy.testing.nose_tools.nosetester', 'six', 'numpy._distributor_init', 'os', 'numpy.linalg.linalg', 'urllib.error', 'numpy.matrixlib', '_ast', 'socket', 'shutil', '_posixsubprocess', 'numpy.polynomial', 'matplotlib.cbook._backports', '_weakrefset', 'numpy.ma', 'encodings.utf_8', 'numpy.lib.stride_tricks', 'codecs', 'zlib', '_frozen_importlib_external', 'numpy.ctypeslib', 'unittest', 'numpy.lib.ufunclike', 'numpy._globals', 'cycler', 'unittest.loader', 'six.moves', '_random', 'random', 'difflib', '_bootlocale', 'matplotlib.cbook.deprecation', 'numpy.random.mtrand', 'numpy.core.function_base', 'distutils.sysconfig', 'numpy.ma.core', 'stat', 'numpy.core.shape_base', 'email.quoprimime', 'dateutil', '_io', '_sysconfigdata', 'numpy.fft.info', '_json', 'certifi.core', 'numpy.fft.fftpack_lite', 'email.parser', 'sitecustomize', 'numpy.core.multiarray', 'numpy.__config__', '_compat_pickle', 'numpy.lib.format', 'errno', 'email', 'numpy.fft', 'operator', 'numpy.lib.financial', 'numpy.linalg', 'numpy.core.getlimits', 'os.path', 'pprint', '__future__', 'math', '__main__', '_compression', '_string', 'numpy.linalg.lapack_lite', 'sys', 'textwrap', 'numpy.random.info', 'matplotlib.testing', 'six.moves.urllib.request', '_struct', 'ctypes', 'unittest.runner', 'fnmatch', '_lzma', 'numpy._import_tools', 'handle_logging_lib', 'numpy.core', 'numpy.compat.py3k', 'numpy.lib', 'numpy.core.arrayprint', 'numpy.core.info', '_collections_abc', 'posix', '_sitebuiltins', 'linecache', 'http.client', 'weakref', 'signal', 'importlib._bootstrap', '_decimal', 'numpy.core.numerictypes', 'sysconfig', 'urllib.request', 'dis', 'numpy.lib.arraypad', 'copy', 'urllib', 'atexit', 'logging', 'email.iterators', 'keyword', '_pickle', 'rlcompleter', 'cython_runtime', 'numpy', 'numpy.testing', 'pwd', 'importlib.abc', '_opcode', 'numpy.core.machar', 'tokenize', 'distutils.errors', 'email.header', 'calendar', 'traceback', 'numpy.lib.mixins']
DEBUG:matplotlib:CACHEDIR=/home/pi/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /home/pi/.cache/matplotlib/fontList.json
DEBUG:matplotlib:$HOME=/home/pi
DEBUG:matplotlib:matplotlib data path /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data
DEBUG:matplotlib:loaded rc file /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/matplotlibrc
DEBUG:matplotlib:matplotlib version 2.2.2
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
DEBUG:matplotlib:loaded modules: ['distutils', 'six', '_pickle', 'importlib.abc', 'numpy.lib._iotools', 'json.encoder', 'urllib.response', 'numpy.lib.format', 'numpy.random.mtrand', 'importlib.util', 'numpy.ma', '_random', 'numpy.random.info', 'numpy.lib.stride_tricks', 'pathlib', 'numpy.lib.arraypad', 'grp', 'posixpath', 'random', 'email.feedparser', 'email._parseaddr', 'numpy.version', 'io', 'pprint', 'numpy.matrixlib.defmatrix', 'six.moves.urllib', 'numpy.core.function_base', 'matplotlib', 'numpy.polynomial.chebyshev', '_compat_pickle', 'functools', 'unittest.util', 'decimal', 'uu', 'shutil', 'math', 'distutils.sysconfig', 'subprocess', 'distutils.version', 'numpy.testing.decorators', 'rlcompleter', 'tokenize', 'os', 'numpy.lib.nanfunctions', 'pwd', '_signal', 'dis', 'numpy.fft', 'fnmatch', 'numpy.polynomial', 'certifi.core', '_sre', 'numpy.core.machar', 'datetime', 'collections.abc', 'lzma', 'matplotlib.cbook._backports', 'unittest.suite', 'ast', 'readline', '_weakrefset', 'abc', 'builtins', 'email.quoprimime', '_lzma', 'encodings.aliases', '_socket', 'contextlib', 'numpy.lib._version', 'importlib.machinery', 'numpy.polynomial.laguerre', 'six.moves', 'numpy.core.shape_base', 'numpy', 'matplotlib.rcsetup', 'selectors', 'plot_weather_lib', 'mpl_toolkits', 'numpy.compat', '_functools', 'inspect', 'matplotlib._version', 'bisect', 'gettext', 'handle_logging_lib', 'unittest.result', '_sysconfigdata_m', 'email', 'site', 'json', '_bz2', 'numpy.lib', 'numpy.linalg.linalg', 'bz2', 'numpy.core.multiarray', '_heapq', 'numpy.testing.nose_tools.decorators', 'ntpath', 'email.errors', '_frozen_importlib', 'sre_parse', 'atexit', 'numpy.lib.arrayterator', 'numpy.ctypeslib', 'numpy.linalg', 'importlib', 'six.moves.urllib.request', 'numpy.lib.index_tricks', 'numpy.core.einsumfunc', 'numpy.linalg.info', 'numpy.matrixlib', 'numpy.lib.npyio', 'unittest.case', 'numpy.lib.ufunclike', 'numpy.lib.twodim_base', 'numpy._distributor_init', 'email.charset', '_locale', 'operator', 'numpy.core.arrayprint', '_struct', 'numpy.fft.fftpack_lite', 'weakref', 'marshal', 'numpy.core.memmap', '_collections_abc', 'pyparsing', 'numpy.linalg._umath_linalg', 'numpy.core._internal', 'numpy.core.records', '_posixsubprocess', 'email.parser', 'itertools', 'socket', 'ssl', 'difflib', 'numpy.core.getlimits', '_sitebuiltins', 'matplotlib.cbook.deprecation', 'zipimport', 'numpy.lib.info', '_json', 'gzip', 'numpy.lib.scimath', 'sre_constants', 'keyword', 'urllib.parse', 'sre_compile', 'distutils.errors', 'email._policybase', 'numpy.core.umath', 'argparse', '_opcode', 'glob', '_weakref', 'urllib', 'importlib._bootstrap', 'json.decoder', 'linecache', '_hashlib', 'numpy.core.numerictypes', 'cycler', 'collections', 'heapq', 'numpy.polynomial.polynomial', 'binascii', 'sys', 'numpy._globals', '_operator', 'numpy.lib.arraysetops', 'numpy.add_newdocs', 'numpy.lib._datasource', 'numpy.ma.core', 'numpy.testing.nose_tools.utils', 'numpy.lib.financial', 'copyreg', 'warnings', 're', 'numpy.lib.mixins', 'matplotlib.fontconfig_pattern', 'struct', 'numpy.fft.helper', 'sitecustomize', 'posix', 'sysconfig', 'opcode', 'numpy.core', 'pickle', '_sysconfigdata', '_ast', 'email.utils', '_ctypes', 'json.scanner', 'string', 'unittest.loader', 'email.message', 'numpy.polynomial.hermite', 'unittest', 'numpy.lib.function_base', 'stat', 'threading', '_decimal', 'numpy.compat.py3k', 'numpy.__config__', 'email.header', 'matplotlib.testing', 'encodings.latin_1', 'numpy.polynomial._polybase', '_imp', 'time', 'signal', 'locale', 'numbers', '__main__', '_datetime', 'quopri', 'certifi', 'numpy.core.defchararray', '_warnings', 'matplotlib._color_data', 'token', 'numpy.core._methods', 'urllib.request', '_bisect', '_frozen_importlib_external', 'email._encoded_words', 'numpy.core.fromnumeric', 'matplotlib.compat', 'os.path', 'unittest.signals', 'numpy.random', 'numpy.core.info', 'base64', 'numpy.testing.utils', '__future__', '_string', 'numpy.linalg.lapack_lite', 'logging', 'numpy.testing.nosetester', 'cython_runtime', 'numpy.polynomial.polyutils', 'numpy.core.numeric', 'select', '_compression', 'ipaddress', 'enum', 'numpy.lib.polynomial', 'numpy.testing', 'numpy.lib.shape_base', 'matplotlib.colors', 'numpy.testing.nose_tools.nosetester', 'unittest.main', 'numpy.lib.utils', '_thread', '_ssl', 'numpy.polynomial.hermite_e', 'reprlib', '_io', 'codecs', 'urllib.error', 'dateutil._version', 'copy', 'dateutil', 'errno', 'encodings', 'numpy.lib.type_check', 'email.encoders', 'numpy.fft.info', 'numpy.fft.fftpack', 'matplotlib.cbook', 'numpy.testing.nose_tools', 'matplotlib.compat.subprocess', 'traceback', '_stat', 'numpy.ma.extras', 'ctypes', 'tempfile', 'mtrand', 'numpy.polynomial.legendre', 'numpy.compat._inspect', '_bootlocale', 'genericpath', 'zlib', 'email.base64mime', 'importlib._bootstrap_external', 'unittest.runner', '_codecs', 'types', 'numpy._import_tools', '_collections', 'encodings.utf_8', 'http', 'hashlib', 'email.iterators', 'http.client', 'ctypes._endian', 'textwrap', 'calendar']
DEBUG:matplotlib:CACHEDIR=/home/pi/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /home/pi/.cache/matplotlib/fontList.json
DEBUG:matplotlib.backends:backend agg version v2.2
DEBUG:matplotlib:$HOME=/home/pi
DEBUG:matplotlib:matplotlib data path /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data
DEBUG:matplotlib:loaded rc file /home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/matplotlibrc
DEBUG:matplotlib:matplotlib version 2.2.2
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is linux
DEBUG:matplotlib:loaded modules: ['_lzma', '_pickle', '_bz2', '_opcode', '_frozen_importlib_external', 'numpy.lib', 'numpy.compat', 'signal', '_sysconfigdata', 'unittest.result', 'email.feedparser', 'numpy.testing.utils', 'string', 'matplotlib.fontconfig_pattern', 'numpy', 'heapq', 'site', 'numpy.core.memmap', 'numpy.polynomial.chebyshev', 'importlib._bootstrap_external', 'email._encoded_words', 'certifi', 'io', 'hashlib', 'os.path', 'select', 'numpy.lib.utils', '_ctypes', 'numpy.linalg', '_sitebuiltins', 'numpy.core._internal', 'numbers', 'numpy.testing.nose_tools', 'numpy.core.defchararray', 'warnings', 'numpy.polynomial.polyutils', '_operator', 'email._parseaddr', 'sre_parse', 'distutils.version', 'dateutil._version', '_datetime', 'functools', 'numpy.lib.ufunclike', 'base64', 'quopri', 'numpy.lib.format', 'email.header', 'numpy.core.machar', 'atexit', '_io', '_hashlib', 'numpy.core.numerictypes', '_bootlocale', 'numpy.lib.type_check', 'unittest.case', 'numpy.polynomial._polybase', 'pickle', 'numpy.matrixlib', 'email', 'cython_runtime', 'numpy.matrixlib.defmatrix', 'plot_weather_lib', 'numpy.fft.helper', '__main__', '_stat', 'numpy.lib.arrayterator', '_sysconfigdata_m', 'bz2', 'readline', 'numpy.polynomial', 'numpy.lib.mixins', 'zlib', 'argparse', 'numpy.lib.info', 'matplotlib.compat.subprocess', 'ctypes._endian', 'numpy.random.mtrand', '_bisect', 'numpy.lib.npyio', '_frozen_importlib', 'marshal', 'numpy.random.info', 'numpy._import_tools', 'numpy.linalg.linalg', '_weakref', 'numpy.lib.stride_tricks', 'encodings.utf_8', 'unittest.suite', 'struct', 'pprint', 'email.quoprimime', 'numpy.core.records', 'ssl', 'decimal', 'numpy.fft.fftpack', '_string', 'urllib.response', 'numpy.lib.polynomial', 'types', 'sre_compile', 'locale', 'email.iterators', 'numpy.testing.nose_tools.decorators', 'enum', 'importlib.machinery', '_struct', 'numpy.core.einsumfunc', '_locale', 'numpy.linalg._umath_linalg', 'subprocess', 'stat', '_warnings', 'numpy.core.fromnumeric', '_signal', 'numpy.polynomial.hermite_e', 'six.moves', '_codecs', 'handle_logging_lib', 'unittest', 'dateutil', 'six', '_imp', '_random', 'builtins', 'numpy.polynomial.legendre', 'logging', 'fnmatch', 'importlib.util', 'keyword', 'importlib._bootstrap', 'urllib', 'numpy.lib._iotools', 'distutils.sysconfig', 'matplotlib.colors', 'dis', 'numpy.ma.extras', 'numpy.core._methods', 'email.base64mime', 'traceback', 'genericpath', 'matplotlib', 'matplotlib.rcsetup', 'numpy.core.function_base', 'numpy._globals', 'numpy.lib.index_tricks', 'numpy.testing.nosetester', 'unittest.main', 'ipaddress', 'numpy.fft.fftpack_lite', 'numpy.lib.shape_base', 'matplotlib.cbook.deprecation', 'importlib.abc', 'calendar', 'numpy.testing.decorators', 'json.encoder', 'gzip', 'http.client', 'numpy.compat._inspect', 'numpy.add_newdocs', 'codecs', 'binascii', '_ast', 'weakref', 'numpy.__config__', 'collections', 'unittest.util', 'matplotlib.testing', 'sysconfig', 'distutils', 'numpy.core.arrayprint', 'copy', 'matplotlib.cbook', 'six.moves.urllib', 'numpy.core.shape_base', 'urllib.parse', 'ast', 'email.charset', 'pyparsing', 'email.encoders', 'operator', 'numpy.core.numeric', 'numpy.core.info', 'mpl_toolkits', 'ctypes', 'math', 'mtrand', 'abc', 'urllib.request', 'encodings.aliases', 'numpy.lib._version', 'importlib', 'json.decoder', 'email.parser', '_collections', 'numpy.lib.financial', 'pwd', '__future__', 'email.utils', 'matplotlib._color_data', '_functools', 'json.scanner', 'grp', 'numpy.polynomial.hermite', '_decimal', 'numpy.lib.nanfunctions', 'difflib', 'unittest.runner', 'unittest.loader', 'unittest.signals', 'numpy.lib._datasource', 'numpy.linalg.lapack_lite', 'numpy.polynomial.laguerre', '_compression', 'bisect', '_compat_pickle', 'numpy.lib.arraysetops', 'opcode', 'linecache', 'email.errors', 'tempfile', 'rlcompleter', 'random', 'numpy.core.getlimits', 'inspect', 'six.moves.urllib.request', 'selectors', 'numpy.core.umath', 'numpy.lib.twodim_base', 're', 'tokenize', 'distutils.errors', '_thread', 'certifi.core', 'encodings', 'os', 'token', 'numpy._distributor_init', 'numpy.linalg.info', 'zipimport', 'numpy.ma.core', 'threading', 'uu', '_collections_abc', 'lzma', 'datetime', 'numpy.core', 'numpy.ma', 'numpy.testing.nose_tools.utils', '_weakrefset', 'numpy.fft', 'numpy.lib.arraypad', 'posixpath', 'numpy.version', 'sre_constants', 'copyreg', 'glob', 'numpy.lib.scimath', 'http', 'time', 'textwrap', 'email.message', 'email._policybase', 'numpy.ctypeslib', 'numpy.random', 'numpy.lib.function_base', 'cycler', 'pathlib', 'shutil', 'socket', '_posixsubprocess', '_sre', 'json', 'encodings.latin_1', 'sys', 'urllib.error', 'itertools', 'numpy.core.multiarray', 'sitecustomize', 'collections.abc', 'numpy.fft.info', 'posix', 'matplotlib.cbook._backports', 'reprlib', 'ntpath', 'numpy.testing', 'contextlib', '_ssl', 'gettext', 'matplotlib.compat', 'matplotlib._version', '_socket', '_heapq', 'errno', 'numpy.polynomial.polynomial', 'numpy.compat.py3k', '_json', 'numpy.testing.nose_tools.nosetester']
DEBUG:matplotlib:CACHEDIR=/home/pi/.cache/matplotlib
DEBUG:matplotlib.font_manager:Using fontManager instance from /home/pi/.cache/matplotlib/fontList.json
DEBUG:matplotlib.backends:backend agg version v2.2
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.darksky.net
DEBUG:urllib3.connectionpool:https://api.darksky.net:443 "GET /forecast/d3fbc403cc28523a125c3c5ab8e43ded/47.649093,-122.199153 HTTP/1.1" 200 29712
DEBUG:matplotlib.font_manager:findfont: Matching :family=sans-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to DejaVu Sans ('/home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf') with score of 0.050000
DEBUG:matplotlib.font_manager:findfont: Matching :family=sans-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=14.0 to DejaVu Sans ('/home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf') with score of 0.050000
DEBUG:matplotlib.font_manager:findfont: Matching :family=sans-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=16.0 to DejaVu Sans ('/home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf') with score of 0.050000
